name: Tang, Michael
description: a website for me!
author: Michael Tang

author_email: super@mtang.co

paginate: 10

# baseurl: http://tangmichael.com
url: http://tangmichael.com/

markdown: redcarpet

highlighter: pygments
permalink: /:title/

exclude: [
  README.md,
  Gemfile,
  Gemfile.lock,
  CNAME,
  package.json,
  gulpfile.js,
  node_modules
  ]

gems:
  # - jekyll-sitemap
  # - jemoji
  # - jekyll-sass-converter
  # - jekyll-mentions
  - 'github-pages'