name: Tang, Michael
description: a website to display my talents
author: Michael Tang

author_email: super@mtang.co

paginate: 10

# baseurl: http://tangmichael.com
url: http://tangmichael.com/

markdown: redcarpet

highlighter: pygments
permalink: /:title/

exclude: [README.md, Gemfile, Gemfile.lock, CNAME]

gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-sass-converter